version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
     - "9090:8080"
    volumes:
      - .:/go/src/app
    tty:
      true
    security_opt:
      - seccomp:unconfined
